### ISSUE TITLE
create a 0.6 tag for whatever is in the 0.6 release

### ISSUE THREAD

**Issue by willkg** [jbalogh/django-multidb-router#21]
Can someone create a 0.6 tag for whatever went out in the 0.6 release so there's a record?

**Comment by willkg** [comment]
Judging by commit dates and PyPI, I'm guessing it's cad620f1f28d0b0991218608184bbf6c3a9cccc0.

**Comment by jsocol** [comment]
Done!

**Comment by jsocol** [comment]
(I `git blame`d setup.py and picked the commit that changed the version to 0.6, which was the one you found.)

**Comment by willkg** [comment]
Awesome! Thank you @jsocol!
