### ISSUE TITLE
Support new-style Middleware specifications (Django >= 1.10)

### ISSUE THREAD

**Issue by mawkee** [jbalogh/django-multidb-router#38]
Currently, multidb-router only implements an old-style middleware. We need to add support for 1.10+ middlewares. As a quick experience, simply inheriting from MiddlewareMixin does the trick, as specified here

https://docs.djangoproject.com/en/2.0/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

**Comment by diox** [comment]
Hi,

Patches implementing this are welcome :)
