### ISSUE TITLE
s/slave/read-replica (or similar)

### ISSUE THREAD

**Issue by jsocol** [jbalogh/django-multidb-router#44]
~I don't think I have commit access here anymore,~ (oh maybe I do!) but it would be great to replace the master/slave terminology as it's a fairly easy/backwards-compatible change to make (e.g. read `DATABASE_REPLICAS` if defined, else fallback)

**Comment by diox** [comment]
Agreed. There are quite a few references to change, but it should be fairly straightforward. I'll gladly review a PR implementing that :)

**Comment by jsocol** [comment]
I'm on it! Should have something shortlyish. Need to rebase on the Django version change

**Comment by jsocol** [comment]
Fixed by #45
