### ISSUE TITLE
How to use when multi databases are replicated ?

### ISSUE THREAD

**Issue by mced** [jbalogh/django-multidb-router#52]
I have several databases living on their own and each are replicated.
How to use this lib with this kind of multi databases setup ?

**Comment by diox** [comment]
https://github.com/jbalogh/django-multidb-router/blob/master/README.rst ?

**Comment by mced** [comment]
@diox I will explicit my use case;
I have 2 main databases which store different tables and each of these are replicated.

Something that looks like:
```python
DATABASES = {
    'default': {...},
    'default-slave-1': {...},
    'default-slave-2': {...},

    'timeseries': {...},
    'timeseries-slave-1': {},
    'timeseries-slave-2': {},    
}
```

I guess that using the following will use `timeseries-slave-...` replicas as `default` replica which is not...
```python
REPLICA_DATABASES = [
   'default-slave-1', 'default-slave-2', 'timeseries-slave-1', 'timeseries-slave-2'
]
```

**Comment by diox** [comment]
Sorry, django-multidb-router doesn't support this use-case.
