### ISSUE TITLE
Use a configurable list of views as a @db_write alternative for GET requests that change the database

### ISSUE THREAD

**Issue by aptiko** [jbalogh/django-multidb-router#7]
The way to tell `django-multidb-router` that a GET request changes the database is to use the `db_write` decorator or to `set response._db_write = True`. This has the problem that it's not possible to add `django-multidb-router` to an existing Django application without changing application code (if the Django application changes the database with GET requests). How about adding a setting, for `settings.py`, that specifies a list of views that change the database even when they're GET?

**Comment by diox** [comment]
(copied from the PR I closed earlier)

This is a very old issue, but it deserves a reply... I also don't like having this as a setting in `django-multidb-router` itself.

I don't think it's a good idea to have GET requests altering the database in the first place, so it's best so leave this outside of the app and keep it simple and easy to use - if you need this, you should implement it in your own project, inheriting from `django-multidb-router` classes.
